import { Router, type IRouter } from "express";
import healthRouter from "./health";
import messagesRouter from "./messages";
import callsRouter from "./calls";
import requestsRouter from "./requests";
import tipsRouter from "./tips";
import statsRouter from "./stats";
import postsRouter from "./posts";
import eventsRouter from "./events";
import adminRouter from "./admin";
import chatRouter from "./chat";
import socialRouter from "./social";
import settingsRouter from "./settings";
import aiGenerateRouter from "./ai-generate";
import aiSchedulerRouter from "./ai-scheduler";
import giftCardsRouter from "./gift_cards";
import uploadRouter from "./upload";
import vipRouter from "./vip";
import pushRouter from "./push";

const router: IRouter = Router();

router.use(adminRouter);
router.use(eventsRouter);
router.use(healthRouter);
router.use(messagesRouter);
router.use(callsRouter);
router.use(requestsRouter);
router.use(tipsRouter);
router.use(statsRouter);
router.use(postsRouter);
router.use(chatRouter);
router.use(socialRouter);
router.use(settingsRouter);
router.use(aiGenerateRouter);
router.use(aiSchedulerRouter);
router.use(giftCardsRouter);
router.use(uploadRouter);
router.use(vipRouter);
router.use(pushRouter);

export default router;
